dist: trusty
language: node_js
node_js:
  - "4"

before_install:
  - sudo apt-get update -q
  - sudo apt-get install wine wine-mono -y

install:
  - npm install -g nw@sdk 
  - npm install
  - ln -s ../node_modules ./src/node_modules

script:
  - node build-nw.js

before_deploy:
  - tag=$(git describe --abbrev=0 --tags)
  - cd build/StellarWallet/
  - for dir in *; do zip -r "StellarDesktop${dir^}-${tag}.zip" "$dir"; done
  - rm -rf */
  - ls -al

deploy:
  provider: releases
  api_key:
    secure: 65282935338b16f513d1bf6b31e078a856becc97
  skip_cleanup: true
  file_glob: true
  file: ./*
  on:
    tags: true


notifications:
  email: false